### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by dylanhoryza** [dylanhoryza/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want pre-work notes to be structured on a webpage
so that I can easily find and read information 

## Acceptance Criteria
GIVEN a pre-work Study Guide Website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by immortal-brick** [comment]
Hey I would be happy to help you with that
